### ISSUE TITLE
Include lat and lng in autocomplete

### ISSUE THREAD

**Issue by serval92** [tmentink/jquery.geocomplete#1]
Hi, Trent.

Could you add to your script an automatic geocoding to get lat and lng, please ? It would be very nice !
Thank you.

**Comment by tmentink** [comment]
Hey serval,

You can currently get the lat and lng from the selected place by reading from the `placeResult` which is returned to the `onChange` callback. This would be easiest way to get the lat and lng each time a place is changed:

```javascript
$("#myInput").geocomplete({
  onChange: function(name, result) {
    // this is the LatLng for the selected location
    var location = result.geometry.location;
  }
});

**Comment by serval92** [comment]
Thank you for your answer really fast !
I'm going to study that.

**Comment by tvbishan** [comment]
I have tried `var location = result.geometry.location;`. But couldn't get the lat and lng from the selected place.

Here is my output.
![image](https://user-images.githubusercontent.com/12027448/37394126-10577b0e-2799-11e8-8ee6-0a5f24db2baa.png)

How could I get the lat and lng from the selected place?

**Comment by tmentink** [comment]
`result.geometry.location` is a [LatLng](https://developers.google.com/maps/documentation/javascript/reference/3/#LatLng) class which has the **methods** `lat()` and `lng()`

```javascript
$("#myInput").geocomplete({
  onChange: function(name, result) {
    // this is the LatLng for the selected location
    var location = result.geometry.location;
    var lat = location.lat();
    var lng = location.lng();
  }
});

**Comment by tvbishan** [comment]
Thanks for the quick response. really appreciate.
